cp-zookeeper:
  enabled: true
  servers: 1
  image: confluentinc/cp-zookeeper
  imageTag: 5.5.0
  imagePullSecrets:
  heapOptions: "-Xms256M -Xmx256M"
  persistence:
    enabled: true
    dataDirSize: 256Mi
    dataLogDirSize: 256Mi
  resources: {}

cp-kafka:
  enabled: true
  brokers: 1
  configurationOverrides:
    offsets.topic.replication.factor: 1
    confluent.metrics.reporter.topic.replicas: 1
  image: confluentinc/cp-enterprise-kafka
  imageTag: 5.5.0
  imagePullSecrets:
  heapOptions: "-Xms256M -Xmx256M"
  persistence:
    enabled: true
    size: 256Mi
    disksPerBroker: 1
  resources: {}

cp-schema-registry:
  enabled: false
  image: confluentinc/cp-schema-registry
  imageTag: 5.5.0
  imagePullSecrets:
  heapOptions: "-Xms256M -Xmx256M"
  resources: {}

cp-kafka-rest:
  enabled: false
  image: confluentinc/cp-kafka-rest
  imageTag: 5.5.0
  imagePullSecrets:
  heapOptions: "-Xms256M -Xmx256M"
  resources: {}

cp-kafka-connect:
  enabled: false
  image: confluentinc/cp-kafka-connect
  imageTag: 5.5.0
  imagePullSecrets:
  heapOptions: "-Xms256M -Xmx256M"
  resources: {}

cp-ksql-server:
  enabled: false
  image: confluentinc/cp-ksqldb-server
  imageTag: 5.5.0
  imagePullSecrets:
  heapOptions: "-Xms256M -Xmx256M"
  ksql:
    headless: false

cp-control-center:
  enabled: false
  image: confluentinc/cp-enterprise-control-center
  imageTag: 5.5.0
  imagePullSecrets:
  heapOptions: "-Xms256M -Xmx256M"
  resources: {}