apiVersion: v1
kind: Secret
metadata:
  name: order-secret
type: Opaque
data:
  dbuser: {{ printf "%s" .Values.postgresql.postgresqlUsername | b64enc | quote }}
  dbpswd: {{ printf "%s" .Values.postgresql.postgresqlPassword | b64enc | quote }}