FROM maven:3.6.3-jdk-8 as builder
LABEL maintainer="Dubinina Yulia"
RUN mkdir /app
WORKDIR /app
COPY otus_architect_task_7_model otus_architect_task_7_model
COPY otus_architect_task_7_order otus_architect_task_7_order
WORKDIR /app/otus_architect_task_7_model
RUN mvn clean install
WORKDIR /app/otus_architect_task_7_order
RUN mvn clean package


######## Start a new stage #######
FROM openjdk:8  
RUN mkdir /app
WORKDIR /app
COPY --from=builder /app/otus_architect_task_7_order/target/otus_architect_task_7_order-0.0.1-SNAPSHOT.jar .
EXPOSE 8080 
ENTRYPOINT ["java", "-jar", "otus_architect_task_7_order-0.0.1-SNAPSHOT.jar"]